# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  kind:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Kind
      run: |
        GO111MODULE="on" go get sigs.k8s.io/kind@v0.7.0
        kind create cluster
    - name: Testing
      run: |
        kubectl cluster-info
        kubectl get pods -A
        echo "current-context:" $(kubectl config current-context)
        echo "environment-kubeconfig:" ${KUBECONFIG}
        curl -sSL https://cli.openfaas.com | sudo -E sh
        kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml
        helm repo add openfaas https://openfaas.github.io/faas-netes/
        helm upgrade openfaas --install openfaas/openfaas     --namespace openfaas      --set functionNamespace=openfaas-fn     --set generateBasicAuth=true
        kubectl port-forward --address 0.0.0.0 svc/gateway -n openfaas 8080:8080 &
        sleep 30
        kubectl get pods -A
        export PASSWORD=$(kubectl -n openfaas get secret basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode)
        echo -n $PASSWORD | faas-cli login --username=admin --password-stdin
        faas-cli new test --lang python3
